spring:
  datasource:
    url: jdbc:mysql://localhost:31306/security?useUnicode=true&characterEncoding=UTF-8&ServerTimeZone=Asia/Shanghai
    username: root
    password: sa
    driver-class-name: com.mysql.jdbc.Driver